version: '3.8'

services:
  rtm-mcp:
    build: .
    ports:
      - "8733:8733"
    environment:
      # RTM API credentials (set these in your environment or .env file)
      - RTM_API_KEY=${RTM_API_KEY}
      - RTM_SHARED_SECRET=${RTM_SHARED_SECRET}
      - RTM_AUTH_TOKEN=${RTM_AUTH_TOKEN}
      # MCP Bearer token for authentication
      - RTM_MCP_AUTH_TOKEN=${RTM_MCP_AUTH_TOKEN}
      - CF_ACCESS_TEAM_DOMAIN=puddingnet.cloudflareaccess.com
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8733/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
